/*
 * This source file was generated by the Gradle 'init' task
 */
package java_basics;

public class App {

    public static void main(String[] args) {
        System.out.println("Main does nothing");
    }
}
